pub use crate::easy::happy_number;
pub use crate::easy::plus_one;
pub use crate::medium::detect_squares;
pub use crate::medium::multiply_strings;
pub use crate::medium::pow_x_n;
pub use crate::medium::reverse_integer;
pub use crate::medium::rotate_image;
pub use crate::medium::set_matrix_zeroes;
pub use crate::medium::spiral_matrix;
